name: rafale
version: '0.0.5'
summary: Deploy every services, everywhere, in just a few seconds
description: |
  Rafale lets you deploy FortressJS services everywhere

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:

  rafale-service:
    command: rafale --daemon
    daemon: simple
    restart-condition: always
    plugs: [network-bind, home, network]

  rafale:
    command: rafale
    plugs: [network-bind, home, network]

  rfl:
    command: rfl
    plugs: [network-bind, home, network]

parts:
  rafale:
    source: .
    plugin: nodejs
